version: 'latest'

services:
  home-assistant:
    container_name: homeassistant_omie
    image: ghcr.io/home-assistant/home-assistant:2025.1.1
    environment:
      - TZ=UTC
    ports:
      - "9123:8123"
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
    command: >
      python -m homeassistant --config /config
