name: Validate with HACS Action

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v2"
        - uses: hacs/action@21.12.1
          with:
            category: 'integration'
