name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "5 01 * * 1"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: home-assistant/actions/hassfest@master
